name: "38-gh-pages-deploy-frontend — Deploy to GitHub Pages"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout local code
      uses: actions/checkout@v2
      with:
         path: 'this_repo'
    
    - name: Debug Env Variables and list files
      run: |
        THIS_REPO="${{github.repository}}"
        SOURCE_REPO="${THIS_REPO/-docs/}"
        echo "DOCS_SOURCE_REPO=${{vars.DOCS_SOURCE_REPO}}"
        echo "github.repository=${{github.repository}}"
        echo "THIS_REPO=${THIS_REPO}"
        echo "SOURCE_REPO=${SOURCE_REPO}"
        echo "SOURCE_REPO=${SOURCE_REPO}" >> $GITHUB_ENV
        pwd
        ls -lRt
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ env.SOURCE_REPO }}
    
    - name: list files
      run: |
        pwd
        ls -lRt

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install NPM packages
      run: npm ci
      working-directory: frontend

    - name: Build Storybook
      working-directory: frontend
      run: | # Install npm packages and build the Storybook files
        npx build-storybook --docs
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: frontend/storybook-static # The folder the action should deploy.
        branch: gh-pages
